src/Web/ServiceApp.Web/Controllers/OffersController.cs
namespace ServiceApp.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using ServiceApp.Services.DataServices.Contracts;
    using ServiceApp.Services.Models.Offers;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;

    [Authorize]
    public class OffersController : Controller
    {
        private IOfferService offerService;
        private ICarService carService;
        private IPartService partService;
        private readonly IUserService userService;

        public OffersController(IOfferService offerService, ICarService carService, IPartService partService,
            IUserService userService)
        {
            this.offerService = offerService;
            this.carService = carService;
            this.partService = partService;
            this.userService = userService;
        }

        public IActionResult GetAll()
        {
            var offers = this.offerService.GetAll(this.User.FindFirstValue(ClaimTypes.NameIdentifier));
            return View(offers);
        }

        public IActionResult Create()
        {
            this.ViewData["carsRegisterNums"] = this.carService.GetAll(this.User.FindFirstValue(ClaimTypes.NameIdentifier))
                .Select(
                x=>new SelectListItem
                {
                    Value = x.RegistrationNum,
                    Text= x.RegistrationNum
                }
                );

            var parts = this.partService.GetAllFromWarehouse(this.userService.GetById(this.User.FindFirstValue(ClaimTypes.NameIdentifier)).WarehouseId).Select(o=>o.Description);
            ViewBag.parts = parts;

            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(OfferCreateViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var id = await offerService.Create(input);

            return RedirectToAction("Details", new { id = id });
        }
        

        public IActionResult Details(int id)
        {
            var offer = offerService.GetById(id);

            return this.View(offer);
        }
    }
}

src/Web/ServiceApp.Web/Views/Offers/Create.cshtml
@using ServiceApp.Services.Models.Offers

@model OfferCreateViewModel

@{
    var carsRegisterNums = this.ViewData["carsRegisterNums"] as IEnumerable<SelectListItem>;
    var parts = this.ViewBag.parts;
}

@*Fix the view with select list items for the parts*@
<form asp-controller="Offers" asp-action="Create" method="post">
    <h4>Избери автомобил</h4>
    @*Избор по регистрационен номер*@

    <div class="form-group">
        <label asp-for="CarRegistrationNumber" class="control-label">Регистрационен номер</label>

        <div >
            <input asp-for="CarRegistrationNumber" type="text" list="carsRegisterNums" />
            <datalist id="carsRegisterNums">
                @foreach (var regNum in carsRegisterNums)
                {
                    <option>@regNum.Text</option>
                }
            </datalist>
        </div>
        <span asp-validation-for="CarRegistrationNumber" class="text-danger"></span>
    </div>


    <a href="#" id="add" class="btn btn-default">Добави ред</a>
    <div class="form-group" id="item-list">
        <br />
        <input asp-for="Raws" name="Raws[0].Part" type="text" list="parts" />
        <datalist id="parts">
            @foreach (var part in parts)
            {
                <option value="@part"></option>
            }
        </datalist>
        @*<input type="text" asp-for="Raws" class="items" name="Raws[0].Part.PartPrice" value="" />*@
        <input type="text" asp-for="Raws" class="items" name="Raws[0].Count" value="" />
        <input type="text" asp-for="Raws" class="items" name="Raws[0].PriceOfWork" value="" />
    </div>

    <input type="submit" value="Създай" class="btn btn-primary" />

</form>

@section Scripts {
    <script>
        $(function () {

            $("#add").click(function (e) {
                e.preventDefault();
                var i = ($(".items").length) / 4;
                var n = '<br />' +
                    '<input type="text" asp-for="Raws" style="margin: 5px 5px 5px 0;" name="Raws[' + i + '].PartDesciption" />' +
                    '<input type="text" asp-for="Raws" style="margin: 5px 5px 5px 0;" name="Raws[' + i + '].PartPrice" />' +
                    '<input type="text" asp-for="Raws" style="margin: 5px 5px 5px 0;" name="Raws[' + i + '].Count" />' +
                    '<input type="text" asp-for="Raws" style="margin: 5px 5px 5px 0;" name="Raws[' + i + '].PriceOfWork" />'


                $("#item-list").append(n);
            });

        });

        $(document).ready(function () {
            $('#registerNumber').on('change', function () {
                var optionText = $('#registerNumber option:selected').text();
                alert("Selected Option Text: " + optionText);
            })
        });
    </script>
}

src/Web/ServiceApp.Web/Views/Offers/Details.cshtml
@using ServiceApp.Services.Models.Offers

@model OfferDetailsViewModel

<div class="jumbotron">
    <div>
        <span>@Model.CarMake</span>
    </div>
    <div>
        <span>@Model.CarModel</span>
    </div>
    <div>
        <span>@Model.CarRegistrationNumber</span>
    </div>
    <div>
        <span>@Model.CarVinNumber</span>
    </div>

    <div class="container-fluid">
        <table class="table table-striped">
            <tr>
                <th>№</th>
                <th>Код на частта</th>
                <th>Описание</th>
                <th>Цена</th>
                <th>Количество</th>
                <th>Цена части</th>
                <th>Цена за труд</th>
                <th>Цена за реда</th>
            </tr>
            @foreach (var item in Model.Raws)
            {
            <tr>
                <td></td>
                <td>@item.PartCode</td>
                <td>@item.PartDesciption</td>
                <td>@item.PartPrice</td>
                <td>@item.PartCount</td>
                <td>@item.PriceOfParts</td>
                <td>@item.PriceOfWork</td>
                <td>@item.TotalPrice</td>
            </tr>
            }
        </table>
    </div>
</div>
    

src/Web/ServiceApp.Web/Views/Offers/GetAll.cshtml
@{
}
@using ServiceApp.Services.Models

@model IEnumerable<OffersShortViewModel>


<div id="create-offer-btn">
    <a asp-controller="Offers" asp-action="Create" class="btn btn-primary">+ Нова Оферта</a>
</div>
   

<div class="container-fluid">
    <table class="table table-striped">
        <tr>
            <th>№</th>
            <th>Марка</th>
            <th>Рег номер</th>
            <th>Дата на създаване</th>
            <th>Цена</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td></td>
                <td>@item.CarMake</td>
                <td>@item.RegistrationNum</td>
                <td>@item.DateOfCreation</td>
                <td>@item.TotalPrice</td>
            </tr>
        }
    </table>
</div>