src/Web/ServiceApp.Web/Controllers/CarOwnerController.cs
namespace ServiceApp.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using ServiceApp.Services.DataServices.Contracts;
    using ServiceApp.Services.Models.CarOwner;
    using ServiceApp.Web.Areas.Identity.Data;
    using System.Security.Claims;
    using System.Threading.Tasks;

    [Authorize]
    public class CarOwnerController : Controller
    {
        private ICarOwnerService carOwnerService;
        private UserManager<ServiceAppUser> userManager;

        public CarOwnerController(ICarOwnerService carOwnerService, UserManager<ServiceAppUser> userManager)
        {
            this.carOwnerService = carOwnerService;
            this.userManager = userManager;
        }
        

        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CarOwnerCreateViewModel model)
        {
            ServiceAppUser currentUser = await this.userManager.GetUserAsync(HttpContext.User);

            var id = await this.carOwnerService.Create(model,currentUser);

            return this.RedirectToAction("Details", new { id });
        }

        public IActionResult Details(int id)
        {
            var carOwner = carOwnerService.GetById(id);

            return this.View(carOwner);
        }

        public IActionResult GetAll()
        {
            var carOwners = this.carOwnerService.GetAll(this.User.FindFirstValue(ClaimTypes.NameIdentifier));

            return this.View(carOwners);
        }
    }
}

src/Web/ServiceApp.Web/Controllers/CarsController.cs
namespace ServiceApp.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using ServiceApp.Services.DataServices.Contracts;
    using ServiceApp.Services.Models.Cars;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;

    [Authorize]
    public class CarsController : Controller
    {
        private ICarService carService;
        private ICarOwnerService carOwnerService;

        public CarsController(ICarService carService, ICarOwnerService carOwnerService)
        {
            this.carService = carService;
            this.carOwnerService = carOwnerService;
        }

        public IActionResult GetAll()
        {
            var cars = this.carService.GetAll(this.User.FindFirstValue(ClaimTypes.NameIdentifier));

            return View(cars);
        }

        public IActionResult Create()
        {
            this.ViewData["CarOwners"] = this.carOwnerService.GetAll(this.User.FindFirstValue(ClaimTypes.NameIdentifier))
                .Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Name
                }
                );

            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CarCreateViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var id =  await this.carService.Create(model);

            return this.RedirectToAction("Details", new { id = id });
        }


        public IActionResult Details(int id)
        {
            var car = carService.GetById(id);

            return this.View(car);
        }
    }
}

src/Web/ServiceApp.Web/Views/CarOwner/Create.cshtml
@using ServiceApp.Services.Models.CarOwner

@model CarOwnerCreateViewModel

<form asp-controller="CarOwner" asp-action="Create" method="post">
    <h4>Данни за клиента</h4>
    <div class="form-group">
        <label asp-for="Name" class="control-label">Име</label>
        <input asp-for="Name" class="form-control" rows="6" cols="50">
    </div>
    <div class="form-group">
        <label asp-for="Bulstat" class="control-label">Булстат</label>
        <input asp-for="Bulstat" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Address" class="control-label">Адрес</label>
        <input asp-for="Address" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="City" class="control-label">Град</label>
        <input asp-for="City" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="MRP" class="control-label">МОЛ</label>
        <input asp-for="MRP" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Email" class="control-label">Email</label>
        <input asp-for="Email" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Telephone" class="control-label">Телефон</label>
        <input asp-for="Telephone" class="form-control">
    </div>

    <input type="submit" value="Create" class="btn btn-primary" />
</form>

src/Web/ServiceApp.Web/Views/CarOwner/Details.cshtml
@using ServiceApp.Data.Models

@model CarOwner

<div class="jumbotron">
    <h4>@Model.Name</h4>
    <h5>@Model.Bulstat</h5>
    <h5>@Model.City</h5>
    <h5>@Model.Address</h5>
    <h5>@Model.MRP</h5>
    <h5>@Model.Telephone</h5>
    <h5>@Model.Email</h5>

    <h3>Коли</h3>
    <div class="container-fluid">
        <table class="table table-striped">
            <tr>
                <th>Марка</th>
                <th>Модел</th>
                <th>Рег номер</th>
                <th>Номер на рама</th>
            </tr>
            @foreach (var car in Model.Cars)
            {
                <tr>
                    <td>@car.Make</td>
                    <td>@car.CarModel</td>
                    <td>@car.RegistrationNum</td>
                    <td>@car.VinNumber</td>
                    <td> <a asp-controller="Cars" asp-action="Details" asp-route-id="@car.Id">Детайли</a></td>
                </tr>

               
            }
        </table>
    </div>
</div>

src/Web/ServiceApp.Web/Views/CarOwner/GetAll.cshtml
@using ServiceApp.Services.Models.CarOwner

@model IEnumerable<CarOwnerViewModel>

<div id="create-offer-btn">
    <a asp-controller="CarOwner" asp-action="Create" class="btn btn-primary">+ Нов клиент</a>
</div>

<div class="container-fluid">
    @if (Model.Count() == 0)
    {
        <h4>Все още нямате регистрирани клиенти</h4>
    }
    else
    {
        <div class="container-fluid">
            <table class="table table-striped">
                <tr>
                    <th>Име</th>
                    <th>Булстат</th>
                    <th>Град</th>
                    <th>Адрес</th>
                    <th>Задължение</th>
                    <th>Телефон</th>
                </tr>
                @foreach (var client in Model)
                {
                <tr>
                    <td>@client.Name</td>
                    <td>@client.Bulstat</td>
                    <td>@client.City</td>
                    <td>@client.Address</td>
                    <td>@client.Obligation</td>
                    <td>@client.Telephone</td>
                    <td><a asp-controller="CarOwner" asp-action="Details" asp-route-id="@client.Id" class="btn btn-primary">Детайли</a></td>
                </tr>
                    
                }
            </table>
        </div>
    }
</div>